github:
    user: 2binfree
    password: ~
    token: 982fc243cf6d8ac548971b8b9454f0d0f8ebc0f2
    base_url: https://api.github.com
    auth_method: token

linkedin:
    user:
    baseURL:
    clientID:
    clientSecret:


